### PR TITLE
NaxRiscv update for compatibility with naxriscv branches of rvls/risc-isa-sim

### PR DESCRIPTION
**Pull request by Bill94l**
- https://github.com/SpinalHDL/NaxRiscv/issues/126#issue-2661517504

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi ^^ 

I pushed a fix concerning verlator git having migrated to github.
Now the issue seems that NaxRiscv scala binding with RVLS is expecting a more recent version of RVLS.
in particular, it expects that a few of the API return a boolean value to tell if it succeed or not.
Typicaly a feature which was added with this commit : 
https://github.com/SpinalHDL/rvls/commit/35c276a79289f08e0694bce9c277c88ec80de174

**Comment by Dolu1990** [comment]
Ahhh no, the PR you opened need to also update the rvls/riscv-isa-sim.

What you need to do is : 

```shell
cd NaxRiscv
git add ext/rvls
git add ext/riscv-isa-sim
git commit -m "Update rvls/riscv-isa-sim"
git push
```

This way, the submodule update will be included in your change :D

**Comment by Dolu1990** [comment]
For this aswell, you need to do a  : 

```scala
cd NaxRiscv
git add ext/SpinalHDL
git commit -m "Update SpinalHDL"
git push
``` 

Then this update should show up in this PR.
Basicaly, that git submodule update would become part of the PR. (instead of relying on the main repo having the same version as you already)

**Comment by Dolu1990** [comment]
https://github.com/SpinalHDL/riscv-isa-sim/pull/4 merged ^^

**Comment by Bill94l** [comment]
I don't know what's wrong with Verilator ?

**Comment by Dolu1990** [comment]
Hmm weird, i'm looking at it. Probably a new version of GCC not so happy with it XD

**Comment by Dolu1990** [comment]
The verilator compilation should be good now ^^

**Comment by Dolu1990** [comment]
BRAwwwwwww it passes regression <3

**Comment by Bill94l** [comment]
Great! 😄

We also have an updated version featuring a global `Makefile` and scripts that automate the local installation of the toolchain without requiring `sudo`.

- This version allows you to run all regression tests, including booting Linux with RVLS through SocSim.

If you're interested, I'd be happy to prepare a new pull request! 😊

**Comment by Dolu1990** [comment]
Sure, no sudo is good  ^^

**Comment by Dolu1990** [comment]
All good for merging this PR ?
(the detected conflict, i will solve that)

**Comment by Bill94l** [comment]
Yes, everything works perfectly for this PR on my side. The regression tests successfully pass for all RV32 and RV64 configurations using RVLS. Regarding the conflict, I'm unsure of its cause, as riscv-isa-sim was merged without any issues.

**Comment by Dolu1990** [comment]
The 
Merge remote-tracking branch 'origin/rvls-update' into updated-spike
did nothing, that was just to get ride of github issues ^^
Nothing was merged yet in SpinalHDL org.

But right now it is merged ^^

**Pull request merged**
